// import router from '@/router'
export default{
    reducemodify(state){
        state.currentindex--
        state.currentindexs--
        if(state.currentindex<0){
            state.currentindex=state.songlist.length-1
            state.currentindexs=state.songlist.length-1
        }
    },
    addmodify(state){
        state.currentindex++
        state.currentindexs++
        if(state.currentindex>state.songlist.length-1){
            state.currentindex=0
            state.currentindexs=0
        }
    },
    addfirst(state){
        state.first.zan++
    },
    removefirst(state){
        state.first.zan--
    },
    isbofang(state){
        console.log('???')
        state.isbofang=!state.isbofang
    }
}